import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Arkar Yan - Full Stack Developer | Software Architect | Project Manager",
  description: "Visionary Software Architect and Educator with 10+ years experience. Led 200+ projects in enterprise SaaS, AI solutions, and cybersecurity advocacy. Founder of k Square, specializing in MERN, Laravel, and Flutter development.",
  keywords: [
    "Arkar Yan",
    "Software Engineer",
    "Full Stack Developer",
    "Project Manager",
    "Instructor",
    "Founder",
    "Software Architect",
    "MERN",
    "Laravel",
    "Flutter",
    "Cybersecurity",
    "SaaS",
    "Next.js",
    "React.js",
    "Node.js",
    "PHP",
    "Web Development",
    "Mobile Development",
    "k Square",
    "Myanmar Cyber Ghost",
    "TypeScript",
    "Tailwind CSS",
    "Portfolio",
    "Software Development",
    "Enterprise Solutions",
    "AI Solutions",
  ],
  authors: [{ name: "Arkar Yan" }],
  creator: "Arkar Yan",
  publisher: "Arkar Yan",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL("https://arkaryan.net/"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "Arkar Yan - Full Stack Developer & Software Architect",
    description: "10+ years experience in software architecture, project management, and cybersecurity advocacy. Founder of k Square and Myanmar Cyber Ghost.",
    type: "website",
    url: "https://arkaryan.net/",
    siteName: "Arkar Yan - Portfolio",
    locale: "en_US",
    images: [
      {
        url: "/profile.jpg",
        width: 1200,
        height: 630,
        alt: "Arkar Yan - Full Stack Developer & Software Architect",
      },
      {
        url: "/profile.jpg",
        width: 1200,
        height: 1200,
        alt: "Arkar Yan - Full Stack Developer & Software Architect",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Arkar Yan - Full Stack Developer & Software Architect",
    description: "10+ years experience in software architecture, project management, and cybersecurity advocacy. Founder of k Square.",
    images: ["/profile.jpg"],
    creator: "@hidecard1",
    site: "@hidecard1",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    google: "your-google-verification-code",
    yandex: "your-yandex-verification-code",
  },
};
